import React, { createContext, useContext, useMemo, useState } from 'react';
import { applyDocumentLanguage, getSavedLanguage } from '../utils/language';

const messages = {
  en: {
    common: {
      language: 'Language',
      arabic: 'Arabic',
      english: 'English',
      switchToArabic: 'Switch to Arabic',
      switchToEnglish: 'Switch to English',
      backToDashboard: 'Back to Dashboard',
      messages: 'messages',
      loading: 'Loading...',
      today: 'Today',
      yesterday: 'Yesterday',
      delete: 'Delete',
    },
    header: {
      premium: 'Get Premium',
      morning: 'Good Morning',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening',
      lightMode: 'Switch to light mode',
      darkMode: 'Switch to dark mode',
      notifications: 'Notifications',
      noNotifications: 'No new notifications',
      profile: 'Profile',
      signOut: 'Sign Out',
    },
    nav: {
      mainMenu: 'Main Menu',
      dashboard: 'Dashboard',
      exercises: 'Exercises',
      aiChatbot: 'AI Chatbot',
      foodScanner: 'Food Scanner',
      profile: 'Profile',
      achievements: 'Achievements',
      community: 'Community',
      freePlan: 'Free Plan',
    },
    dashboard: {
      todaysWorkout: "Today's Workout",
      fullBodyStrength: 'Full Body Strength',
      workoutMeta: '6 exercises · 45 min · Intermediate',
      startWorkout: 'Start Workout',
      hydration: 'Hydration',
      hydrated: 'Hydrated',
      leftToday: '{amount} ml left today',
      goalComplete: 'Daily goal complete',
      undo: 'Undo',
      resetToday: 'Reset today',
      hydrationGoal: 'Hydration goal',
      readiness: 'Readiness',
      readinessCopy: 'Recovery check before training',
      trainToday: 'Train today, keep rest periods honest.',
      sleep: 'Sleep',
      recovery: 'Recovery',
      strain: 'Strain',
      bestNextBlock: 'Best next block',
      strengthSession: '45 min strength session',
      strengthCopy: 'Log a protein-focused meal after training to keep today on track.',
      progressHub: 'Progress Hub',
      weeklyOverview: 'Weekly performance overview',
      weekTrend: '+12% this week',
      caloriesBurned: 'Calories Burned',
      unlocked: 'unlocked',
      workouts: 'Workouts',
      weeklyGoal: 'weekly goal',
      nutrition: 'Nutrition',
      kcalRemaining: 'kcal remaining',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      scanNextMeal: 'Scan next meal',
      dailyDose: 'Daily Dose',
      tapNext: 'Tap to see next ->',
      proPlan: 'Pro Plan',
      unlockElite: 'Unlock Elite Features',
      upgradeCopy: 'Advanced AI coaching, full analytics, unlimited food scans and priority support.',
      upgradeNow: 'Upgrade Now',
    },
    chat: {
      title: 'AI Coach',
      subtitle: 'Your personal 24/7 fitness and nutrition expert',
      history: 'History',
      coach: 'ATOS fit Coach',
      ready: 'Online & Ready',
      welcome: "Hello! I'm your AI fitness coach. How can I assist you today?",
      fallback: 'Sorry, I am currently unable to process your request.',
      historyTitle: 'Chat History',
      refreshHistory: 'Refresh History',
      newChat: 'New Chat',
      noPast: 'No past conversations',
      msgs: 'msgs',
      promptBeginner: 'Workout plan for beginners',
      promptMeal: 'Post-workout meal?',
      promptPrep: 'Healthy meal prep',
      promptForm: 'Improve my form',
      input: 'Ask your AI coach anything...',
    },
    scanner: {
      title: 'Food Scanner',
      subtitle: 'Analyze your meals instantly with AI',
      frame: 'Food Frame',
      savedScans: '{count} saved scans',
      upload: 'Upload Image',
      emptyTitle: 'Scan your meal',
      emptyCopy: 'Upload a clear food photo and ATOS will estimate the nutrition.',
      reading: 'Reading the plate',
      complete: 'Scan Complete',
      ready: 'Ready to Scan',
      result: 'Analysis Result',
      noData: 'No Data',
      protein: 'Protein',
      carbs: 'Carbs',
      fats: 'Fats',
      saved: 'Saved in History',
      autoSave: 'Successful scans save automatically',
      recent: 'Recent Scans',
      noHistory: 'No history yet',
      deleteScan: 'Delete scan',
      unknownFood: 'Unknown Food',
      error: 'Error Analyzing',
    },
    exercises: {
      library: 'Exercise Library',
      intro: 'Browse exercises, preset plans, or create your own',
      exercises: 'Exercises',
      presetPlans: 'Preset Plans',
      createPlan: 'Create Plan',
      search: 'Search exercises by name, muscles, or description...',
      all: 'All',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      noExercises: 'No exercises found',
      adjustFilters: 'Try adjusting your search or filter criteria',
      clearFilters: 'Clear Filters',
      createCustom: 'Create Custom Workout Plan',
      createCopy: 'Build your own personalized workout plan using our exercise library',
      startBuilding: 'Start Building Plan',
      customPlans: 'Your Custom Plans',
      planExercises: '{count} exercises',
      startPlan: 'Start Plan',
      deletePlan: 'Are you sure you want to delete this plan?',
    },
    achievements: {
      title: 'Achievements',
      subtitle: 'View your earned badges, milestones, and goals',
    },
    community: {
      title: 'Community Hub',
      subtitle: 'Connect, share, and grow together with ATOSfit',
      hero: 'The Ultimate Fitness Network',
      heroCopy: 'A dedicated social platform designed for your fitness journey. Track progress, inspire others, and build a network of driven individuals.',
      launching: 'Launching Soon',
      expect: 'What to Expect',
      expectCopy: 'Be the first to know when our community features launch.',
      challenges: 'Challenges',
      goals: 'Goals',
      advice: 'Advice',
      share: 'Share Your Workouts',
      shareCopy: 'Connect with friends and the ATOSfit community. Share your sessions, progress, and achievements.',
      engage: 'Create & Engage',
      engageCopy: 'Post about your fitness journey, share tips, and engage with other members through likes and comments.',
      support: 'Support & Motivation',
      supportCopy: "Like and comment on other members' workouts to build a supportive fitness community.",
      social: 'Social Integration',
      socialCopy: 'Share your workout achievements to X, Facebook, or Instagram stories seamlessly.',
    },
    profile: {
      personalInfo: 'Personal Info',
      fitnessMetrics: 'Fitness Metrics',
      memberFor: 'Member for',
      active: 'Active',
      workouts: 'Workouts',
      dayStreak: 'Day Streak',
      uploadDevice: 'Upload from device',
      takePhoto: 'Take photo',
      removePhoto: 'Remove photo',
      updatePicture: 'Update profile picture',
      save: 'Save',
      cancel: 'Cancel',
      notProvided: 'Not provided',
      fullName: 'Full Name',
      email: 'Email Address',
      birthDate: 'Date of Birth',
      accountSettings: 'Account Settings',
      appearance: 'Appearance',
      appearanceCopy: 'Switch between light and dark mode',
      toggleTheme: 'Toggle Theme',
    },
    auth: {
      signInTitle: 'Sign in to ATOS fit',
    },
  },
  ar: {
    common: {
      language: 'اللغة',
      arabic: 'العربية',
      english: 'English',
      switchToArabic: 'التبديل إلى العربية',
      switchToEnglish: 'التبديل إلى الإنجليزية',
      backToDashboard: 'العودة إلى لوحة التحكم',
      messages: 'رسالة',
      loading: 'جار التحميل...',
      today: 'اليوم',
      yesterday: 'أمس',
      delete: 'حذف',
    },
    header: {
      premium: 'اشترك بريميوم',
      morning: 'صباح الخير',
      afternoon: 'مساء الخير',
      evening: 'مساء الخير',
      lightMode: 'التبديل إلى الوضع الفاتح',
      darkMode: 'التبديل إلى الوضع الداكن',
      notifications: 'الإشعارات',
      noNotifications: 'لا توجد إشعارات جديدة',
      profile: 'الملف الشخصي',
      signOut: 'تسجيل الخروج',
    },
    nav: {
      mainMenu: 'القائمة الرئيسية',
      dashboard: 'لوحة التحكم',
      exercises: 'التمارين',
      aiChatbot: 'المدرب الذكي',
      foodScanner: 'ماسح الطعام',
      profile: 'الملف الشخصي',
      achievements: 'الإنجازات',
      community: 'المجتمع',
      freePlan: 'الخطة المجانية',
    },
    dashboard: {
      todaysWorkout: 'تمرين اليوم',
      fullBodyStrength: 'قوة الجسم بالكامل',
      workoutMeta: '6 تمارين · 45 دقيقة · متوسط',
      startWorkout: 'ابدأ التمرين',
      hydration: 'الترطيب',
      hydrated: 'مرطب',
      leftToday: 'متبقي اليوم {amount} مل',
      goalComplete: 'اكتمل هدف اليوم',
      undo: 'تراجع',
      resetToday: 'إعادة ضبط اليوم',
      hydrationGoal: 'هدف الترطيب',
      readiness: 'الجاهزية',
      readinessCopy: 'مراجعة التعافي قبل التدريب',
      trainToday: 'تدرب اليوم وحافظ على فترات راحة منضبطة.',
      sleep: 'النوم',
      recovery: 'التعافي',
      strain: 'الإجهاد',
      bestNextBlock: 'أفضل خطوة تالية',
      strengthSession: 'جلسة قوة لمدة 45 دقيقة',
      strengthCopy: 'سجل وجبة غنية بالبروتين بعد التمرين لتبقى على المسار الصحيح.',
      progressHub: 'مركز التقدم',
      weeklyOverview: 'نظرة على أداء الأسبوع',
      weekTrend: '+12% هذا الأسبوع',
      caloriesBurned: 'السعرات المحروقة',
      unlocked: 'مفتوح',
      workouts: 'التمارين',
      weeklyGoal: 'الهدف الأسبوعي',
      nutrition: 'التغذية',
      kcalRemaining: 'سعرة متبقية',
      protein: 'البروتين',
      carbs: 'الكربوهيدرات',
      fat: 'الدهون',
      scanNextMeal: 'امسح الوجبة التالية',
      dailyDose: 'جرعة اليوم',
      tapNext: 'اضغط لرؤية النصيحة التالية',
      proPlan: 'خطة برو',
      unlockElite: 'افتح المزايا المتقدمة',
      upgradeCopy: 'تدريب ذكي متقدم وتحليلات كاملة ومسح وجبات غير محدود ودعم أولوية.',
      upgradeNow: 'ترقية الآن',
    },
    chat: {
      title: 'المدرب الذكي',
      subtitle: 'خبير لياقة وتغذية شخصي متاح طوال اليوم',
      history: 'السجل',
      coach: 'مدرب ATOS الذكي',
      ready: 'متصل وجاهز',
      welcome: 'أهلا بك، أنا مدربك الذكي للياقة. كيف أساعدك اليوم؟',
      fallback: 'عذرا، لا أستطيع معالجة طلبك الآن.',
      historyTitle: 'سجل المحادثات',
      refreshHistory: 'تحديث السجل',
      newChat: 'محادثة جديدة',
      noPast: 'لا توجد محادثات سابقة',
      msgs: 'رسائل',
      promptBeginner: 'خطة تمرين للمبتدئين',
      promptMeal: 'وجبة بعد التمرين؟',
      promptPrep: 'تحضير وجبات صحية',
      promptForm: 'حسن أدائي',
      input: 'اسأل مدربك الذكي أي شيء...',
    },
    scanner: {
      title: 'ماسح الطعام',
      subtitle: 'حلل وجباتك فورا بالذكاء الاصطناعي',
      frame: 'إطار الوجبة',
      savedScans: '{count} عمليات مسح محفوظة',
      upload: 'رفع صورة',
      emptyTitle: 'امسح وجبتك',
      emptyCopy: 'ارفع صورة واضحة للطعام وسيقدر ATOS قيمتها الغذائية.',
      reading: 'جار قراءة الوجبة',
      complete: 'اكتمل المسح',
      ready: 'جاهز للمسح',
      result: 'نتيجة التحليل',
      noData: 'لا توجد بيانات',
      protein: 'البروتين',
      carbs: 'الكربوهيدرات',
      fats: 'الدهون',
      saved: 'محفوظ في السجل',
      autoSave: 'يتم حفظ عمليات المسح الناجحة تلقائيا',
      recent: 'عمليات المسح الأخيرة',
      noHistory: 'لا يوجد سجل بعد',
      deleteScan: 'حذف عملية المسح',
      unknownFood: 'طعام غير معروف',
      error: 'تعذر التحليل',
    },
    exercises: {
      library: 'مكتبة التمارين',
      intro: 'تصفح التمارين والخطط الجاهزة أو أنشئ خطتك',
      exercises: 'التمارين',
      presetPlans: 'الخطط الجاهزة',
      createPlan: 'إنشاء خطة',
      search: 'ابحث باسم التمرين أو العضلات أو الوصف...',
      all: 'الكل',
      beginner: 'مبتدئ',
      intermediate: 'متوسط',
      advanced: 'متقدم',
      noExercises: 'لم يتم العثور على تمارين',
      adjustFilters: 'جرب تعديل البحث أو الفلاتر',
      clearFilters: 'مسح الفلاتر',
      createCustom: 'إنشاء خطة تمرين مخصصة',
      createCopy: 'ابن خطتك الشخصية من مكتبة التمارين',
      startBuilding: 'ابدأ بناء الخطة',
      customPlans: 'خططك المخصصة',
      planExercises: '{count} تمارين',
      startPlan: 'ابدأ الخطة',
      deletePlan: 'هل تريد حذف هذه الخطة؟',
    },
    achievements: {
      title: 'الإنجازات',
      subtitle: 'راجع الشارات والأهداف والمراحل التي حققتها',
    },
    community: {
      title: 'مجتمع ATOS',
      subtitle: 'تواصل وشارك وتقدم مع مجتمع ATOSfit',
      hero: 'شبكة لياقة مصممة لك',
      heroCopy: 'منصة اجتماعية لرحلتك الرياضية. تابع تقدمك وألهم الآخرين وابن شبكة من الأشخاص الجادين.',
      launching: 'قريبا',
      expect: 'ما الذي ينتظرك',
      expectCopy: 'كن أول من يعرف عند إطلاق مزايا المجتمع.',
      challenges: 'تحديات',
      goals: 'أهداف',
      advice: 'نصائح',
      share: 'شارك تمارينك',
      shareCopy: 'تواصل مع أصدقائك ومجتمع ATOSfit وشارك جلساتك وتقدمك وإنجازاتك.',
      engage: 'أنشئ وتفاعل',
      engageCopy: 'انشر رحلتك الرياضية وشارك النصائح وتفاعل بالإعجابات والتعليقات.',
      support: 'دعم وتحفيز',
      supportCopy: 'ادعم تمارين الأعضاء الآخرين بالإعجاب والتعليق لبناء مجتمع مشجع.',
      social: 'مشاركة اجتماعية',
      socialCopy: 'شارك إنجازاتك الرياضية بسهولة على X وفيسبوك وإنستغرام.',
    },
    profile: {
      personalInfo: 'المعلومات الشخصية',
      fitnessMetrics: 'مقاييس اللياقة',
      memberFor: 'عضو منذ',
      active: 'نشط',
      workouts: 'التمارين',
      dayStreak: 'سلسلة الأيام',
      uploadDevice: 'رفع من الجهاز',
      takePhoto: 'التقاط صورة',
      removePhoto: 'حذف الصورة',
      updatePicture: 'تحديث صورة الملف',
      save: 'حفظ',
      cancel: 'إلغاء',
      notProvided: 'غير متوفر',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      birthDate: 'تاريخ الميلاد',
      accountSettings: 'إعدادات الحساب',
      appearance: 'المظهر',
      appearanceCopy: 'التبديل بين الوضع الفاتح والداكن',
      toggleTheme: 'تبديل المظهر',
    },
    auth: {
      signInTitle: 'تسجيل الدخول إلى ATOS fit',
    },
  },
};

const LanguageContext = createContext(null);

function readMessage(language, key) {
  return key.split('.').reduce((value, part) => value?.[part], messages[language]);
}

function interpolate(value, params) {
  return String(value).replace(/\{(\w+)\}/g, (_, key) => params?.[key] ?? `{${key}}`);
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = getSavedLanguage();
    if (typeof document !== 'undefined') applyDocumentLanguage(saved);
    return saved;
  });

  const setLanguage = (nextLanguage) => {
    const next = nextLanguage === 'ar' ? 'ar' : 'en';
    setLanguageState(next);
    if (typeof document !== 'undefined') applyDocumentLanguage(next);
    try {
      localStorage.setItem('atos_language', next);
    } catch {}
  };

  const value = useMemo(() => ({
    language,
    isRTL: language === 'ar',
    setLanguage,
    toggleLanguage: () => setLanguage(language === 'ar' ? 'en' : 'ar'),
    t: (key, params = {}) => interpolate(readMessage(language, key) ?? readMessage('en', key) ?? key, params),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
